version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-46-137-159-254.eu-west-1.compute.amazonaws.com
            database: d78emns7chh2s3
            user: viziehhtuyysgg
            password: 824d54cbad8a98ab7a0ff3825f2fbb4e051468db6b467cd45ff58b8d53d75fa5
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
